### ISSUE TITLE
cannot convert type 'string' to 'bool'	mc_funcs.mqh

### ISSUE THREAD

**Issue by Mark-Joy** [jseparovic/MQL4CSharp#12]
Hello,

Thank you for your project!!
I am trying to build MQL4Csharp.mq4, but I got many errors with latest MT4 compiler
Could you please update the files in "MQL4CSharp\Mql"?

**Comment by asyncjason** [comment]
I'm not really using this project at the moment. If you could fix the issues and raise a Pull Request I'd be happy to merge it for you.

**Comment by Mark-Joy** [comment]
The thing is I don't know how to correct this issue:

error: cannot convert type 'string' to 'bool'	mc_funcs.mqh
```
case 55:
         return SymbolSelect(params[0], (bool)params[1]);
```

**Comment by asyncjason** [comment]
that's strange. looks like something broke in the latest metatrader.

As per the docs, this type cast should be supported:
https://docs.mql4.com/basis/types/casting
(section "Typecasting for the String Type")

Maybe it's a bug in the latest metatrader?
Check with metaquotes, as I don't see why this should not work.

**Comment by Mark-Joy** [comment]
It seems that converting from string to bool is not supported anymore.
https://www.mql5.com/en/forum/171214
https://www.mql5.com/en/forum/53/page18#comment_3905997

Am I correct to say that param is converted to string before pass to MT4?
Then will the below solve the issue?
SymbolSelect(params[0], StringCompare(params[1],"true",false))

**Comment by asyncjason** [comment]
nice find. I've added the fix here: https://github.com/jseparovic/MQL4CSharp/commit/b698cfe1ffe905c2fff48c3492c4c925e2a168da
Just note that StringCompare returns an int as a result. if the strings are equal, this int is 0
